services:
  db:
    image: postgres:16.3-bookworm
    restart: always
    env_file:
      - ./envs/.env.${APP_ENV:-dev}
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

  web:
    build: .
    depends_on:
      db:
        condition: service_healthy
    env_file:
      - ./envs/.env.${APP_ENV:-dev}
    volumes:
      - .:/app

  pgadmin:
    image: dpage/pgadmin4
    restart: always
    ports:
      - "5050:80"  # Access pgAdmin via localhost:5050
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    volumes:
      - pgadmin_data:/var/lib/pgadmin
    depends_on:
      - db

volumes:
  postgres_data:
  pgadmin_data:
